<?php
/**
 * @file
 * Add menu items for by-role listings.
 */

/**
 * Implements hook_menu().
 */
function role_listings_menu() {
  $items = array();

  // Configuration page

  $items['admin/config/people/role-listings'] = array(
    'title' => 'Role listings',
    'description' => 'Configure the number of users to display in role listings.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('role_listings_settings_form'),
    'file' => 'role_listings.admin.inc',
    'access arguments' => array('administer users'),
    'type' => MENU_NORMAL_ITEM,
  );

  // Overview page

  $items["admin/people/role-users"] = array(
    'title' => 'Role users',
    'description' => 'List all roles and the users with that role.',
    'page callback' => 'role_listings_display',
    'file' => 'role_listings.admin.inc',
    'access arguments' => array('administer users'),
    'type' => MENU_LOCAL_TASK,
  );

  // Add users-by-role for each role. Since the main user management page lets
  // us filter by role in Backdrop, we'll simply redirect to that page with the
  // appropriate filter query.

  $weight = 0;
  $roles = user_roles();
  unset($roles[BACKDROP_ANONYMOUS_ROLE]);
  foreach ($roles as $role_name => $role_label) {
    $items["admin/people/role-users/$role_name"] = array(
      'title' => check_plain($role_label),
      'description' => format_string('List all users with role %role',
        array('%role' => $role_name)),
      'page callback' => 'backdrop_goto',
      'page arguments' => array("admin/people",
        $role_name == BACKDROP_AUTHENTICATED_ROLE ?
        array() : array('query' => array('role' => $role_name))),
      'access arguments' => array('administer users'),
      'weight' => $weight++,
      'type' => MENU_LOCAL_TASK,
    );
  }

  // Special Roles (admin/people/role-users/special-roles) provided by a View.

  // Add permissions-by-role for each role. Note that we have to give the new
  // menu item a distinct path to avoid infinite loop.

  $weight = 0;
  $roles = user_roles();
  foreach ($roles as $role_name => $role_label) {
    $items["admin/config/people/permissions/by-role-$role_name"] = array(
      'title' => check_plain($role_label),
      'description' => format_string('Configure permissions for role %role',
        array('%role' => $role_name)),
      'page callback' => 'backdrop_goto',
      'page arguments' => array("admin/config/people/permissions/$role_name"),
      'access arguments' => array('administer permissions'),
      'weight' => $weight++,
      'type' => MENU_LOCAL_TASK,
    );
  }

  return $items;
}


/**
 * Implements hook_config_info().
 */
function role_listings_config_info() {
  $prefixes['role_listings.settings'] = array(
    'label' => t('Role Listings settings'),
    'group' => t('Configuration'),
  );
  $prefixes['views.view.users_special'] = array(
    'label' => t('Special Roles'),
    'group' => t('Views'),
  );
  return $prefixes;
}
